### PR TITLE
refactor(Radio): update styling

### PR DESCRIPTION
**Pull request by QuiiBz**
## Type

- Refactor

#### What is expected?

Refactor the styling of the Radio component to match the design: https://ultraviolet.scaleway.com/6dd9b5c45/p/712cdc-radio/b/8125d7

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| url  | Screenshot 2023-07-27 at 14 45 21 | Screenshot 2023-07-27 at 14 45 42 |

### CODE REVIEW

**Review by matthprost — APPROVED** [review]

**Comment by PetmePant** [comment]
@QuiiBz 
Following is a list of things I see:

We need to change the children's prop to label to match accessibility standards and alignment with the design
Size is not needed to be exposed in props/code etc since its fixed
I see no helper option available according to the specifications
I see no tab (outline) navigation in the component

**Review by PetmePant — CHANGES_REQUESTED** [review]
Following is a list of things I see:

We need to change the children's prop to label to match accessibility standards and alignment with the design
Size is not needed to be exposed in props/code etc since its fixed
I see no helper option available according to the specifications
I see no tab (outline) navigation in the component

**Comment by PetmePant** [comment]
https://ultraviolet.scaleway.com/6dd9b5c45/p/712cdc-radio/b/82e524

**Comment by QuiiBz** [comment]
@PetmePant I've updated the code to replace the `children` prop with `label`, remove the `size` prop, and added a new `helper` prop to show help text underneath. About the outline, it shows on my side when the radio is focused. Sorry, I'm not very familiar yet with the zeroheight and didn't understand where the props are defined.

**Comment by PetmePant** [comment]
@QuiiBz  `About the outline, it shows on my side when the radio is focused. `

I am speaking about the tab navigation and the outline for accessibility. Is it working on your side?

**Comment by QuiiBz** [comment]
> I am speaking about the tab navigation and the outline for accessibility. Is it working on your side?

If I understand correctly, yes:

https://github.com/scaleway/ultraviolet/assets/43268759/fa4f51e7-3dde-4177-ac5e-80ab49dc9c40

**Comment by PetmePant** [comment]
it should have an extra blue border that we use similar to buttons. 

I summon @matthprost

**Review by fabienhebert — APPROVED** [review]

**Review by PetmePant — APPROVED** [review]

**Pull request merged**
